version: 2.1
orbs:
  node: circleci/node@5
jobs:
  test-node:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
      REACT_NATIVE_PACKAGER_HOSTNAME: localhost # Example
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - node/install-packages:
          pkg-manager: npm
          install-command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: npm run test --ci --runInBand --reporters=default --reporters=jest-junit
      - run:
          name: Lint
          command: npm run lint
      - store_test_results:
          path: ./test-results/
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'  # Replace with actual deployment steps
workflows:
  build-and-test:
    jobs:
      - test-node
      - deploy:
          requires:
            - test-node
