version: 2.1

orbs:
  node: circleci/node@5
  aws-s3: circleci/aws-s3@4.1

jobs:
  test-node:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install jest-junit
      - run:
          name: Run tests
          command: npm run test --ci --runInBand --reporters=default --reporters=jest-junit
      - store_test_results:
          path: ./test-results/

  build-and-deploy:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Web Build Tools
          command: |
            npm install --global expo-cli
            npm install --save-dev webpack webpack-cli
      - run:
          name: Build Web App
          command: npm run build
      - aws-s3/sync:
          from: web-build
          to: s3://reactnstudi
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"

workflows:
  build-test-deploy:
    jobs:
      - test-node
      - build-and-deploy:
          requires:
            - test-node
          context: AWS_CREDENTIALS
