version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.20 # Or a later Node version
    steps:
      - checkout
      - restore_cache: # Cache node_modules to speed up builds
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install --legacy-peer-deps # Use --legacy-peer-deps if needed

      - save_cache: # Save the cache
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Lint
          command: npm run lint # Assuming you have a lint script in package.json

      - run:
          name: Test
          command: npm test # Assuming you have a test script in package.json

      - run:
          name: Build
          command: npm run build # Or react-native run-android/run-ios depending on your platform

      # Example for building an APK (Android)
      - run:
          name: Build APK (Android)
          command: |
            cd android
            ./gradlew assembleRelease # Or assembleDebug for a debug build

      # Example for building an IPA (iOS) - Requires macOS environment
      # - run:
      #     name: Build IPA (iOS)
      #     command: |
      #       # iOS build commands here. Requires Xcode setup in the executor.
      #       # Example: xcodebuild ...

      # Deploy (Example - adjust for your deployment strategy)
      # - deploy:
      #     name: Deploy to Play Store (Android) - Example
      #     requires: [build]
      #     filters:
      #       branches:
      #         ignore: /.*/
      #         only:
      #           - main # Or your release branch
      #     commands:
      #       - # Your Play Store deployment commands here.  Requires appropriate setup.

      # - deploy:
      #     name: Deploy to App Store (iOS) - Example
      #     requires: [build]
      #     filters:
      #       branches:
      #         ignore: /.*/
      #         only:
      #           - main # Or your release branch
      #     commands:
      #       - # Your App Store deployment commands here. Requires appropriate setup.


workflows:
  build_and_deploy:
    jobs:
      - build
