version: 2
jobs:
 build_and_release_android:
    environment:
        # Configure the JVM and Gradle to avoid OOM errors
        _JAVA_OPTIONS: "-Xms512m -Xmx2g"
        GRADLE_OPTS: '-Xmx3g -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx2g -XX:+HeapDumpOnOutOfMemoryError"'
        LC_ALL: en_US.UTF-8
        LANG: en_US.UTF-8
    docker:
        - image: reactnativecommunity/react-native-android
    steps:
        - checkout
        - run: 
            name: bundle install --path vendor/bundle
            command: bundle install --path vendor/bundle
        - run: 
            name: npm i -g envinfo && envinfo
            command: npm i -g envinfo && envinfo
        - run: 
            name: yarn install
            command: yarn install
        - run: 
            name: npx jetify
            command: npx jetify
        - run: 
            name: Install Fastlane 
            command: gem install fastlane
        - run:
            name: bundle install
            command: cd android && bundle install
        - run: 
            name: fastlane beta
            no_output_timeout: 30m
            command: cd android && fastlane beta
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_release_android
